version: "3.8"
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
    env_file:
      - .env 
    command: uvicorn main:app --host ${HOST} --port 8000 --reload

  frontend:
    build:
      context: ./app/frontend-streamlit
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend-streamlit:/app
    stdin_open: true
    tty: true
    env_file:
      - .env 
